language: python
python:
  # - 3.5
  - 3.6
before_install:
  - python --version
install:
  - pip install -e . 
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  - pip install pytest-cov
script: pytest --cov=. tests
after_success:
  - codecov 
