language: python
python:
  - 3.9
before_install:
  - python --version
install:
  - pip install -U pip
  - pip install -r requirements_dev.txt
script: pytest --cov=src tests
after_success:
  - codecov
