language: python
python:
  - 3.6
  - 3.7
before_install:
  - python --version
install:
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  - pip install pytest-cov
script: pytest --cov=src tests
after_success:
  - codecov 
