version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -U pip
            pip install codecov
            pip install pytest-cov
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            pytest -v --cov=src --junitxml=test-results/junit.xml
      - run:
          name: Run linter
          command: |
            flake8 --statistics src/calculator.py
      - store_test_results:
          path: test-results
      - run:
          name: Run codecov
          command: codecov
